import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillGithub, AiFillLinkedin } from "react-icons/ai";
import Image from "next/image";

import design from "../public/design.png";
import code from "../public/code.png";

import makbyte from "../public/makbyte.png";
import DyApp from "../public/DyApp.png";

import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Yusuf khan Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons  dark:text-white">
              Yusuf Khan
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:text-white"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 "
                  href="/Yusuf-Resume.pdf"
                  target="main"
                  download
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h3 className="text-2xl py-2 md:text-3xl  dark:text-white">
              Frontend Developer
            </h3>
            <p className="text-med py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto  dark:text-white">
              I&apos;m a passionate Frontend Developer with expertise in
              React.js. During my journey in the tech world, I honed my skills
              and gained valuable experience during a rewarding 4-month
              internship at Hometown WebSolutions. My mission is to create
              intuitive, user-friendly web experiences that leave a lasting
              impression. I thrive on turning creative ideas into beautifully
              crafted digital solutions. Explore my portfolio to see some of my
              recent projects and get in touch if you&apos;re interested in
              collaborating or discussing your next exciting project! Let&apos;s
              build the web together 🚀.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a
              href="https://www.linkedin.com/in/yusuf-khan-655340200/"
              target="main"
            >
              <AiFillLinkedin className=" dark:text-white" />
            </a>
            <a
              href="https://github.com/yusufkhan-0912?tab=repositoriesn/yusuf-khan-655340200/"
              target="main"
            >
              <AiFillGithub className=" dark:text-white" />
            </a>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 my-4 font-bold text-center dark:text-white">
              Skills
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800  dark:text-white md:text-lg font-medium">
              Skilled web developer proficient in HTML, CSS, JavaScript, React,
              and Tailwind CSS. Excels in creating dynamic and responsive web
              applications with a keen eye for design. Eager to leverage
              technical expertise in contributing to innovative projects.
            </p>
          </div>
          <div className="lg:flex gap-10 justify-center">
            <div className=" grid justify-center text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white">
              <Image src={code} width={100} height={100} alt="codeimg" />
              {/* <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Design
              </h3> */}
              <h3 className="py-4 text-teal-600 font-medium p-5">
                Language & Libraries
              </h3>

              <p className="text-gray-800 py-1">HTML</p>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">ReactJS</p>
            </div>
            <div className=" grid justify-center text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={design} width={100} height={100} alt="designimg" />
              <h3 className="text-lg font-medium pt-8  py-4 text-teal-600 p-5">
                Frameworks & Tools
              </h3>

              <p className="text-gray-800 py-1">Tailwind CSS</p>
              <p className="text-gray-800 py-1">Bootstrap</p>
              <p className="text-gray-800 py-1">Git</p>
            </div>
          </div>
        </section>
        <section>
          <div className="grid text-center mt-10">
            <h3 className="text-3xl py-1 font-bold  mb-5 dark:text-white">
              Projects
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800  dark:text-white md:text-lg font-medium">
              &quot;I&apos;m a web developer with expertise in HTML, CSS, and
              JavaScript. I create responsive, user-friendly web applications
              with a focus on clean design. Passionate about problem-solving and
              committed to staying updated on industry trends. Ready to
              contribute to dynamic projects and collaborative teams.&quot;
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 text-center">
              <Image
                src={makbyte}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt="Projectimg"
              />
              <div className="flex justify-center gap-10">
                <a href="https://makbyte.io/" target="main">
                  <button className="text-lg font-bold mt-2  border-2 text-white p-1 bg-teal-600 rounded-lg ">
                    Live Demo
                  </button>
                </a>
                <a
                  href="https://github.com/yusufkhan-0912?tab=repositories"
                  target="main"
                >
                  <button className="text-lg font-bold mt-2  border-2 text-white p-1 bg-teal-600 rounded-lg">
                    Github
                  </button>
                </a>
              </div>
            </div>
            <div className="basis-1/3 flex-1 text-center mt-1">
              <Image
                src={DyApp}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt="Projectimg"
              />
              <div className="flex justify-center gap-10">
                <a href="https://dycricketacademy.netlify.app/" target="main">
                  <button className="text-lg font-bold mt-2  border-2 text-white p-1 bg-teal-600 rounded-lg">
                    Live Demo
                  </button>
                </a>
                <a
                  href="https://github.com/yusufkhan-0912?tab=repositories"
                  target="main"
                >
                  <button className="text-lg font-bold mt-2  border-2 text-white p-1 bg-teal-600 rounded-lg">
                    Github
                  </button>
                </a>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
